"use client";
import { useCopyButton } from "fumadocs-ui/utils/use-copy-button";
import {
  AlignJustify,
  Check,
  ChevronsDownUp,
  ChevronsUpDown,
  Clipboard,
  WrapText,
} from "lucide-react";
import {
  type ComponentProps,
  type CSSProperties,
  createContext,
  type HTMLAttributes,
  isValidElement,
  type ReactNode,
  type RefObject,
  use,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { cn } from "../lib/cn";
import { mergeRefs } from "../lib/merge-refs";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./tabs.unstyled";
import { buttonVariants } from "./ui/button";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  "data-language"?: string;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre
      {...props}
      className={cn("min-w-full *:flex *:flex-col", props.className)}
    >
      {props.children}
    </pre>
  );
}

const collapsedLineThreshold = 12;

const languageLabelOverrides: Readonly<Record<string, string>> = {
  abap: "ABAP",
  actionscript: "ActionScript",
  ada: "Ada",
  apache: "Apache",
  apex: "Apex",
  apl: "APL",
  applescript: "AppleScript",
  astro: "Astro",
  awk: "Awk",
  bash: "Bash",
  bat: "Batch",
  batch: "Batch",
  bibtex: "BibTeX",
  c: "C",
  clojure: "Clojure",
  cmake: "CMake",
  cobol: "COBOL",
  codeql: "CodeQL",
  coffeescript: "CoffeeScript",
  commonlisp: "Common Lisp",
  cpp: "C++",
  crystal: "Crystal",
  csharp: "C#",
  css: "CSS",
  csv: "CSV",
  cuda: "CUDA",
  cython: "Cython",
  d: "D",
  dart: "Dart",
  diff: "Diff",
  docker: "Dockerfile",
  dockerfile: "Dockerfile",
  elixir: "Elixir",
  elm: "Elm",
  erb: "ERB",
  erlang: "Erlang",
  ex: "Elixir",
  fortran: "Fortran",
  fsharp: "F#",
  gdscript: "GDScript",
  gherkin: "Gherkin",
  gitcommit: "Git Commit",
  gitrebase: "Git Rebase",
  gleam: "Gleam",
  glsl: "GLSL",
  go: "Go",
  graphql: "GraphQL",
  groovy: "Groovy",
  haml: "Haml",
  handlebars: "Handlebars",
  haskell: "Haskell",
  hcl: "HCL",
  hlsl: "HLSL",
  hs: "Haskell",
  html: "HTML",
  ini: "INI",
  java: "Java",
  javascript: "JavaScript",
  jq: "jq",
  js: "JavaScript",
  json: "JSON",
  json5: "JSON5",
  jsonc: "JSONC",
  jsonl: "JSONL",
  jsx: "JSX",
  julia: "Julia",
  kotlin: "Kotlin",
  kql: "KQL",
  latex: "LaTeX",
  less: "Less",
  liquid: "Liquid",
  lisp: "Lisp",
  lua: "Lua",
  make: "Makefile",
  makefile: "Makefile",
  markdown: "Markdown",
  matlab: "MATLAB",
  md: "Markdown",
  mdx: "MDX",
  mermaid: "Mermaid",
  nginx: "Nginx",
  nim: "Nim",
  nix: "Nix",
  objectivec: "Objective-C",
  objectivecpp: "Objective-C++",
  ocaml: "OCaml",
  pascal: "Pascal",
  perl: "Perl",
  php: "PHP",
  plsql: "PL/SQL",
  postcss: "PostCSS",
  powershell: "PowerShell",
  prisma: "Prisma",
  proto: "Protocol Buffers",
  protobuf: "Protocol Buffers",
  pug: "Pug",
  py: "Python",
  python: "Python",
  r: "R",
  racket: "Racket",
  raku: "Raku",
  razor: "Razor",
  reg: "Reg",
  regex: "RegExp",
  regexp: "RegExp",
  rel: "Rel",
  rst: "reStructuredText",
  rs: "Rust",
  ruby: "Ruby",
  rust: "Rust",
  sass: "Sass",
  scala: "Scala",
  scheme: "Scheme",
  scss: "SCSS",
  shaderlab: "ShaderLab",
  shell: "Shell",
  shellscript: "Shell",
  sh: "Shell",
  smalltalk: "Smalltalk",
  solidity: "Solidity",
  sparql: "SPARQL",
  sql: "SQL",
  svelte: "Svelte",
  swift: "Swift",
  tcl: "Tcl",
  terraform: "Terraform",
  tex: "TeX",
  toml: "TOML",
  ts: "TypeScript",
  tsx: "TSX",
  twig: "Twig",
  typescript: "TypeScript",
  typst: "Typst",
  vb: "Visual Basic",
  verilog: "Verilog",
  vhdl: "VHDL",
  vim: "Vim Script",
  viml: "Vim Script",
  vue: "Vue",
  wasm: "WebAssembly",
  wgsl: "WGSL",
  xml: "XML",
  yaml: "YAML",
  yml: "YAML",
  zig: "Zig",
  zsh: "Zsh",
};

function formatLanguage(value: string) {
  const normalized = value.trim().toLowerCase();
  const override = languageLabelOverrides[normalized];
  if (override) return override;

  return normalized
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function getNodeClassName(node: unknown): string | undefined {
  if (Array.isArray(node)) {
    for (const child of node) {
      const childClassName = getNodeClassName(child);
      if (childClassName) return childClassName;
    }

    return undefined;
  }

  if (!isValidElement(node)) return undefined;

  const props = node.props;
  if (typeof props !== "object" || props === null) return undefined;

  if ("className" in props && typeof props.className === "string") {
    return props.className;
  }

  if (!("children" in props)) return undefined;
  return getNodeClassName(props.children);
}

function getLanguageLabel(
  title: ReactNode,
  className: string | undefined,
  dataLanguage: string | undefined,
  children: ReactNode,
) {
  const classMatch = className?.match(/(?:^|\s)language-([\w-]+)/);
  const childClassMatch = getNodeClassName(children)?.match(
    /(?:^|\s)language-([\w-]+)/,
  );
  const classLanguage = dataLanguage ?? classMatch?.[1] ?? childClassMatch?.[1];

  if (classLanguage) return formatLanguage(classLanguage);
  if (typeof title !== "string") return "Code";

  const extension = title.split(".").at(-1);
  return extension ? formatLanguage(extension) : "Code";
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div {...props} className={cn("empty:hidden", props.className)} />
  ),
  ...props
}: CodeBlockProps) {
  const inTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLElement>(null);
  const [expanded, setExpanded] = useState(false);
  const [wrapCode, setWrapCode] = useState(true);
  const [lineCount, setLineCount] = useState(0);
  const canCollapse = lineCount > collapsedLineThreshold;
  const collapsed = canCollapse && !expanded;
  const languageLabel = getLanguageLabel(
    title,
    props.className,
    props["data-language"],
    children,
  );

  useEffect(() => {
    const pre = areaRef.current?.getElementsByTagName("pre").item(0);
    const text = pre?.textContent;
    setLineCount(text ? text.split("\n").length : 0);
  }, []);

  const toolbar = Actions({
    className:
      "absolute top-3 right-3 z-10 flex origin-top-right  items-center gap-1 border bg-secondary/80 px-2 py-1 text-muted-foreground opacity-0 shadow-lg backdrop-blur-md transition-[opacity,transform] delay-0 duration-200 ease-out group-hover/codeblock:delay-75 group-hover/codeblock:translate-y-0 group-hover/codeblock:scale-100 group-hover/codeblock:opacity-100 group-focus-within/codeblock:delay-75 group-focus-within/codeblock:translate-y-0 group-focus-within/codeblock:scale-100 group-focus-within/codeblock:opacity-100 supports-[backdrop-filter]:bg-secondary/60",
    children: (
      <>
        <span
          data-visible={canCollapse && expanded ? true : undefined}
          className="grid w-0 scale-95 overflow-hidden opacity-0 transition-[width,opacity,transform] duration-100 ease-out data-visible:w-6 data-visible:scale-100 data-visible:opacity-100"
        >
          <CollapseButton onClick={() => setExpanded(false)} />
        </span>
        <span className="px-1 text-xs text-muted-foreground">
          {languageLabel}
        </span>
        <span className="h-4 w-px bg-border" aria-hidden="true" />
        <WrapButton
          wrapped={wrapCode}
          onClick={() => setWrapCode((value) => !value)}
        />
        {allowCopy ? (
          <>
            <span className="h-4 w-px bg-border" aria-hidden="true" />
            <CopyButton containerRef={areaRef} />
          </>
        ) : null}
      </>
    ),
  });
  const viewportStyle: CSSProperties & { "--padding-right"?: string } = {
    counterSet: props["data-line-numbers"]
      ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
      : undefined,
    ...viewportProps.style,
  };

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      data-collapsed={collapsed || undefined}
      data-expanded={canCollapse && expanded ? true : undefined}
      className={cn(
        inTab ? "bg-secondary -mx-px -mb-px" : "my-4 bg-card",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",

        "shiki group/codeblock relative border shadow-sm not-prose overflow-hidden text-sm w-full max-w-full",
        props.className,
      )}
    >
      {title ? (
        <figcaption className="sr-only">
          {typeof title === "string" ? title : languageLabel}
        </figcaption>
      ) : null}
      {typeof icon === "string" ? null : icon}
      {toolbar}
      <section
        ref={areaRef}
        {...viewportProps}
        data-collapsed={collapsed || undefined}
        data-expanded={canCollapse && expanded ? true : undefined}
        data-wrap={wrapCode ? true : undefined}
        className={cn(
          "text-[0.8125rem] overflow-hidden px-5 pt-5 fd-scroll-container transition-[max-height,padding] duration-100 ease-out focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring data-collapsed:max-h-80 data-expanded:max-h-[2400px]",
          wrapCode
            ? "[&_pre]:whitespace-pre-wrap [&_pre]:break-words [&_pre_*]:whitespace-pre-wrap [&_pre_*]:break-words"
            : "overflow-x-auto [&_pre]:w-max [&_pre]:whitespace-pre [&_pre]:break-normal [&_pre_*]:whitespace-pre [&_pre_*]:break-normal",
          canCollapse ? "pb-16" : "pb-4",
          viewportProps.className,
        )}
        style={viewportStyle}
      >
        {children}
      </section>
      {canCollapse ? (
        <>
          {collapsed ? (
            <div
              className="pointer-events-none absolute inset-x-0 bottom-0 bg-linear-to-t from-card via-card/90 to-transparent pb-2 pt-16"
              aria-hidden="true"
            />
          ) : null}
          <div className="pointer-events-none absolute inset-x-0 bottom-0 flex origin-bottom  scale-95 justify-center pb-2 opacity-0 transition-[opacity,transform] delay-0 duration-200 ease-out group-hover/codeblock:delay-75 group-hover/codeblock:translate-y-0 group-hover/codeblock:scale-100 group-hover/codeblock:opacity-100 group-focus-within/codeblock:delay-75 group-focus-within/codeblock:translate-y-0 group-focus-within/codeblock:scale-100 group-focus-within/codeblock:opacity-100">
            <button
              type="button"
              data-collapsed={collapsed || undefined}
              className="pointer-events-auto inline-flex items-center gap-1.5 border bg-secondary/90 px-3 py-1 text-xs text-muted-foreground shadow-sm backdrop-blur-md transition-colors duration-100 ease-out hover:text-accent-foreground [&_svg]:size-3.5"
              onClick={() => setExpanded((value) => !value)}
            >
              <span className="relative grid size-4 place-items-center">
                <ChevronsUpDown
                  data-visible={collapsed || undefined}
                  className="absolute scale-75 opacity-0 transition-[opacity,transform] duration-100 ease-out data-visible:scale-100 data-visible:opacity-100"
                />
                <ChevronsDownUp
                  data-visible={!collapsed || undefined}
                  className="absolute scale-75 opacity-0 transition-[opacity,transform] duration-100 ease-out data-visible:scale-100 data-visible:opacity-100"
                />
              </span>
              <span className="whitespace-nowrap transition-opacity duration-100 ease-out">
                {collapsed ? `Expand (${lineCount} lines)` : "Collapse"}
              </span>
            </button>
          </div>
        </>
      ) : null}
    </figure>
  );
}

function WrapButton({
  wrapped,
  onClick,
}: {
  wrapped: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      data-checked={wrapped || undefined}
      className={cn(
        buttonVariants({
          color: "ghost",
          size: "icon-xs",
          className:
            "hover:text-accent-foreground data-checked:text-accent-foreground",
        }),
      )}
      aria-label={wrapped ? "Disable line wrap" : "Enable line wrap"}
      aria-pressed={wrapped}
      onClick={onClick}
    >
      {wrapped ? <WrapText /> : <AlignJustify />}
    </button>
  );
}

function CollapseButton({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      className={cn(
        buttonVariants({
          color: "ghost",
          size: "icon-xs",
          className: "hover:text-accent-foreground",
        }),
      )}
      aria-label="Collapse code block"
      onClick={onClick}
    >
      <ChevronsDownUp />
    </button>
  );
}

function CopyButton({
  className,
  containerRef,
  ...props
}: ComponentProps<"button"> & {
  containerRef: RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    void navigator.clipboard.writeText(clone.textContent ?? "");
  });

  return (
    <button
      type="button"
      data-checked={checked || undefined}
      className={cn(
        buttonVariants({
          color: "ghost",
          className:
            "hover:text-accent-foreground data-checked:text-accent-foreground",
          size: "icon-xs",
        }),
        className,
      )}
      aria-label={checked ? "Copied Text" : "Copy Text"}
      onClick={onClick}
      {...props}
    >
      {checked ? <Check /> : <Clipboard />}
    </button>
  );
}

export function CodeBlockTabs({ ref, ...props }: ComponentProps<typeof Tabs>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = use(TabsContext) !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={cn(
        "bg-card rounded-xl border",
        !nested && "my-4",
        props.className,
      )}
    >
      <TabsContext
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {props.children}
      </TabsContext>
    </Tabs>
  );
}

export function CodeBlockTabsList(props: ComponentProps<typeof TabsList>) {
  return (
    <TabsList
      {...props}
      className={cn(
        "flex flex-row px-2 overflow-x-auto text-muted-foreground",
        props.className,
      )}
    >
      {props.children}
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({
  children,
  ...props
}: ComponentProps<typeof TabsTrigger>) {
  return (
    <TabsTrigger
      {...props}
      className={cn(
        "relative group inline-flex text-sm font-medium text-nowrap items-center transition-colors gap-2 px-2 py-1.5 hover:text-accent-foreground data-[state=active]:text-primary [&_svg]:size-3.5",
        props.className,
      )}
    >
      <div className="absolute inset-x-2 bottom-0 h-px group-data-[state=active]:bg-primary" />
      {children}
    </TabsTrigger>
  );
}

export function CodeBlockTab(props: ComponentProps<typeof TabsContent>) {
  return <TabsContent {...props} />;
}
