"use client";
import { useCopyButton } from "fumadocs-ui/utils/use-copy-button";
import { Check, ChevronsDownUp, Clipboard } from "lucide-react";
import {
  type ComponentProps,
  type CSSProperties,
  createContext,
  type HTMLAttributes,
  isValidElement,
  type ReactNode,
  type RefObject,
  use,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { cn } from "../lib/cn";
import { mergeRefs } from "../lib/merge-refs";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./tabs.unstyled";
import { buttonVariants } from "./ui/button";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  "data-language"?: string;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre
      {...props}
      className={cn(
        "min-w-full whitespace-pre-wrap break-words *:flex *:flex-col *:whitespace-pre-wrap *:break-words",
        props.className,
      )}
    >
      {props.children}
    </pre>
  );
}

const collapsedLineThreshold = 12;

const languageNames = {
  bash: "Bash",
  sh: "Shell",
  shell: "Shell",
  ts: "TypeScript",
  tsx: "TSX",
  typescript: "TypeScript",
  js: "JavaScript",
  jsx: "JSX",
  javascript: "JavaScript",
  json: "JSON",
  jsonc: "JSONC",
  md: "Markdown",
  mdx: "MDX",
  markdown: "Markdown",
  css: "CSS",
  html: "HTML",
} satisfies Record<string, string>;

function formatLanguage(value: string) {
  switch (value) {
    case "bash":
      return languageNames.bash;
    case "sh":
    case "shell":
      return languageNames.shell;
    case "ts":
    case "typescript":
      return languageNames.typescript;
    case "tsx":
      return languageNames.tsx;
    case "js":
    case "javascript":
      return languageNames.javascript;
    case "jsx":
      return languageNames.jsx;
    case "json":
      return languageNames.json;
    case "jsonc":
      return languageNames.jsonc;
    case "md":
    case "markdown":
      return languageNames.markdown;
    case "mdx":
      return languageNames.mdx;
    case "css":
      return languageNames.css;
    case "html":
      return languageNames.html;
    default:
      return value.toUpperCase();
  }
}

function getNodeClassName(node: unknown): string | undefined {
  if (Array.isArray(node)) {
    for (const child of node) {
      const childClassName = getNodeClassName(child);
      if (childClassName) return childClassName;
    }

    return undefined;
  }

  if (!isValidElement(node)) return undefined;

  const props = node.props;
  if (typeof props !== "object" || props === null) return undefined;

  if ("className" in props && typeof props.className === "string") {
    return props.className;
  }

  if (!("children" in props)) return undefined;
  return getNodeClassName(props.children);
}

function getLanguageLabel(
  title: ReactNode,
  className: string | undefined,
  dataLanguage: string | undefined,
  children: ReactNode,
) {
  const classMatch = className?.match(/(?:^|\s)language-([\w-]+)/);
  const childClassMatch = getNodeClassName(children)?.match(
    /(?:^|\s)language-([\w-]+)/,
  );
  const classLanguage = dataLanguage ?? classMatch?.[1] ?? childClassMatch?.[1];

  if (classLanguage) return formatLanguage(classLanguage);
  if (typeof title !== "string") return "Code";

  const extension = title.split(".").at(-1);
  return extension ? formatLanguage(extension) : "Code";
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div {...props} className={cn("empty:hidden", props.className)} />
  ),
  ...props
}: CodeBlockProps) {
  const inTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLElement>(null);
  const [expanded, setExpanded] = useState(false);
  const [lineCount, setLineCount] = useState(0);
  const canCollapse = lineCount > collapsedLineThreshold;
  const collapsed = canCollapse && !expanded;
  const languageLabel = getLanguageLabel(
    title,
    props.className,
    props["data-language"],
    children,
  );

  useEffect(() => {
    const pre = areaRef.current?.getElementsByTagName("pre").item(0);
    const text = pre?.textContent;
    setLineCount(text ? text.split("\n").length : 0);
  }, []);

  const toolbar = Actions({
    className:
      "absolute top-3 right-3 z-10 flex items-center gap-1 border bg-secondary/80 px-2 py-1 text-muted-foreground shadow-lg backdrop-blur-md supports-[backdrop-filter]:bg-secondary/60",
    children: (
      <>
        {canCollapse && expanded ? (
          <CollapseButton onClick={() => setExpanded(false)} />
        ) : null}
        <span className="px-1 text-xs text-muted-foreground">
          {languageLabel}
        </span>
        {allowCopy ? (
          <>
            <span className="h-4 w-px bg-border" aria-hidden="true" />
            <CopyButton containerRef={areaRef} />
          </>
        ) : null}
      </>
    ),
  });
  const viewportStyle: CSSProperties & { "--padding-right"?: string } = {
    counterSet: props["data-line-numbers"]
      ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
      : undefined,
    ...viewportProps.style,
  };

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        inTab ? "bg-secondary -mx-px -mb-px" : "my-4 bg-card",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",

        "shiki relative border shadow-sm not-prose overflow-hidden text-sm w-full max-w-full",
        props.className,
      )}
    >
      {title ? (
        <figcaption className="sr-only">
          {typeof title === "string" ? title : languageLabel}
        </figcaption>
      ) : null}
      {typeof icon === "string" ? null : icon}
      {toolbar}
      <section
        ref={areaRef}
        {...viewportProps}
        data-collapsed={collapsed || undefined}
        className={cn(
          "text-[0.8125rem] overflow-hidden px-5 pb-16 pt-5 fd-scroll-container focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring data-collapsed:max-h-80",
          viewportProps.className,
        )}
        style={viewportStyle}
      >
        {children}
      </section>
      {canCollapse ? (
        <div
          className={cn(
            "pointer-events-none absolute inset-x-0 bottom-0 flex justify-center pb-2",
            collapsed &&
              "bg-linear-to-t from-card via-card/90 to-transparent pt-16",
          )}
        >
          <button
            type="button"
            className="pointer-events-auto inline-flex items-center gap-1.5 border bg-secondary/90 px-3 py-1 text-xs text-muted-foreground shadow-sm backdrop-blur-md transition-colors hover:text-accent-foreground [&_svg]:size-3.5"
            onClick={() => setExpanded((value) => !value)}
          >
            <ChevronsDownUp />
            {collapsed ? `Expand (${lineCount} lines)` : "Collapse"}
          </button>
        </div>
      ) : null}
    </figure>
  );
}

function CollapseButton({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      className={cn(
        buttonVariants({
          color: "ghost",
          size: "icon-xs",
          className: "hover:text-accent-foreground",
        }),
      )}
      aria-label="Collapse code block"
      onClick={onClick}
    >
      <ChevronsDownUp />
    </button>
  );
}

function CopyButton({
  className,
  containerRef,
  ...props
}: ComponentProps<"button"> & {
  containerRef: RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    void navigator.clipboard.writeText(clone.textContent ?? "");
  });

  return (
    <button
      type="button"
      data-checked={checked || undefined}
      className={cn(
        buttonVariants({
          color: "ghost",
          className:
            "hover:text-accent-foreground data-checked:text-accent-foreground",
          size: "icon-xs",
        }),
        className,
      )}
      aria-label={checked ? "Copied Text" : "Copy Text"}
      onClick={onClick}
      {...props}
    >
      {checked ? <Check /> : <Clipboard />}
    </button>
  );
}

export function CodeBlockTabs({ ref, ...props }: ComponentProps<typeof Tabs>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = use(TabsContext) !== null;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      {...props}
      className={cn(
        "bg-card rounded-xl border",
        !nested && "my-4",
        props.className,
      )}
    >
      <TabsContext
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {props.children}
      </TabsContext>
    </Tabs>
  );
}

export function CodeBlockTabsList(props: ComponentProps<typeof TabsList>) {
  return (
    <TabsList
      {...props}
      className={cn(
        "flex flex-row px-2 overflow-x-auto text-muted-foreground",
        props.className,
      )}
    >
      {props.children}
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({
  children,
  ...props
}: ComponentProps<typeof TabsTrigger>) {
  return (
    <TabsTrigger
      {...props}
      className={cn(
        "relative group inline-flex text-sm font-medium text-nowrap items-center transition-colors gap-2 px-2 py-1.5 hover:text-accent-foreground data-[state=active]:text-primary [&_svg]:size-3.5",
        props.className,
      )}
    >
      <div className="absolute inset-x-2 bottom-0 h-px group-data-[state=active]:bg-primary" />
      {children}
    </TabsTrigger>
  );
}

export function CodeBlockTab(props: ComponentProps<typeof TabsContent>) {
  return <TabsContent {...props} />;
}
