/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as AdminLinksRouteImport } from './routes/admin/links'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiLinkPreviewImageRouteImport } from './routes/api/link-preview-image'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LlmsDotmdxSplatRouteImport } from './routes/llms[.]mdx.$'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin/bootstrap'
import { Route as ApiAnalyticsRumRouteImport } from './routes/api/analytics/rum'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTweetIdRouteImport } from './routes/api/tweet/$id'
import { Route as OgPostsSplatRouteImport } from './routes/og/posts/$'
import { Route as PostsTagsIndexRouteImport } from './routes/posts/tags/index'
import { Route as PostsTagsTagRouteImport } from './routes/posts/tags/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewImageRoute = ApiLinkPreviewImageRouteImport.update({
  id: '/api/link-preview-image',
  path: '/api/link-preview-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxSplatRoute = LlmsDotmdxSplatRouteImport.update({
  id: '/llms.mdx/$',
  path: '/llms.mdx/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRumRoute = ApiAnalyticsRumRouteImport.update({
  id: '/rum',
  path: '/rum',
  getParentRoute: () => ApiAnalyticsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTweetIdRoute = ApiTweetIdRouteImport.update({
  id: '/api/tweet/$id',
  path: '/api/tweet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPostsSplatRoute = OgPostsSplatRouteImport.update({
  id: '/og/posts/$',
  path: '/og/posts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsTagsIndexRoute = PostsTagsIndexRouteImport.update({
  id: '/posts/tags/',
  path: '/posts/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsTagsTagRoute = PostsTagsTagRouteImport.update({
  id: '/posts/tags/$tag',
  path: '/posts/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/links': typeof LinksRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/analytics': typeof ApiAnalyticsRouteWithChildren
  '/api/link-preview-image': typeof ApiLinkPreviewImageRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/$': typeof LlmsDotmdxSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/analytics/rum': typeof ApiAnalyticsRumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/og/posts/$': typeof OgPostsSplatRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/posts/tags/': typeof PostsTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/links': typeof LinksRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/analytics': typeof ApiAnalyticsRouteWithChildren
  '/api/link-preview-image': typeof ApiLinkPreviewImageRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/$': typeof LlmsDotmdxSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/analytics/rum': typeof ApiAnalyticsRumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/og/posts/$': typeof OgPostsSplatRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/posts/tags': typeof PostsTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/links': typeof LinksRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/analytics': typeof ApiAnalyticsRouteWithChildren
  '/api/link-preview-image': typeof ApiLinkPreviewImageRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/$': typeof LlmsDotmdxSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/analytics/rum': typeof ApiAnalyticsRumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/og/posts/$': typeof OgPostsSplatRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/posts/tags/': typeof PostsTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/links'
    | '/llms-full.txt'
    | '/admin/links'
    | '/admin/login'
    | '/api/analytics'
    | '/api/link-preview-image'
    | '/api/search'
    | '/llms.mdx/$'
    | '/posts/$slug'
    | '/posts/'
    | '/api/admin/bootstrap'
    | '/api/analytics/rum'
    | '/api/auth/$'
    | '/api/tweet/$id'
    | '/og/posts/$'
    | '/posts/tags/$tag'
    | '/posts/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/links'
    | '/llms-full.txt'
    | '/admin/links'
    | '/admin/login'
    | '/api/analytics'
    | '/api/link-preview-image'
    | '/api/search'
    | '/llms.mdx/$'
    | '/posts/$slug'
    | '/posts'
    | '/api/admin/bootstrap'
    | '/api/analytics/rum'
    | '/api/auth/$'
    | '/api/tweet/$id'
    | '/og/posts/$'
    | '/posts/tags/$tag'
    | '/posts/tags'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/links'
    | '/llms-full.txt'
    | '/admin/links'
    | '/admin/login'
    | '/api/analytics'
    | '/api/link-preview-image'
    | '/api/search'
    | '/llms.mdx/$'
    | '/posts/$slug'
    | '/posts/'
    | '/api/admin/bootstrap'
    | '/api/analytics/rum'
    | '/api/auth/$'
    | '/api/tweet/$id'
    | '/og/posts/$'
    | '/posts/tags/$tag'
    | '/posts/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LinksRoute: typeof LinksRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRouteWithChildren
  ApiLinkPreviewImageRoute: typeof ApiLinkPreviewImageRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LlmsDotmdxSplatRoute: typeof LlmsDotmdxSplatRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTweetIdRoute: typeof ApiTweetIdRoute
  OgPostsSplatRoute: typeof OgPostsSplatRoute
  PostsTagsTagRoute: typeof PostsTagsTagRoute
  PostsTagsIndexRoute: typeof PostsTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview-image': {
      id: '/api/link-preview-image'
      path: '/api/link-preview-image'
      fullPath: '/api/link-preview-image'
      preLoaderRoute: typeof ApiLinkPreviewImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/$': {
      id: '/llms.mdx/$'
      path: '/llms.mdx/$'
      fullPath: '/llms.mdx/$'
      preLoaderRoute: typeof LlmsDotmdxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/rum': {
      id: '/api/analytics/rum'
      path: '/rum'
      fullPath: '/api/analytics/rum'
      preLoaderRoute: typeof ApiAnalyticsRumRouteImport
      parentRoute: typeof ApiAnalyticsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tweet/$id': {
      id: '/api/tweet/$id'
      path: '/api/tweet/$id'
      fullPath: '/api/tweet/$id'
      preLoaderRoute: typeof ApiTweetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/posts/$': {
      id: '/og/posts/$'
      path: '/og/posts/$'
      fullPath: '/og/posts/$'
      preLoaderRoute: typeof OgPostsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/tags/': {
      id: '/posts/tags/'
      path: '/posts/tags'
      fullPath: '/posts/tags/'
      preLoaderRoute: typeof PostsTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/tags/$tag': {
      id: '/posts/tags/$tag'
      path: '/posts/tags/$tag'
      fullPath: '/posts/tags/$tag'
      preLoaderRoute: typeof PostsTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAnalyticsRouteChildren {
  ApiAnalyticsRumRoute: typeof ApiAnalyticsRumRoute
}

const ApiAnalyticsRouteChildren: ApiAnalyticsRouteChildren = {
  ApiAnalyticsRumRoute: ApiAnalyticsRumRoute,
}

const ApiAnalyticsRouteWithChildren = ApiAnalyticsRoute._addFileChildren(
  ApiAnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  LinksRoute: LinksRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiAnalyticsRoute: ApiAnalyticsRouteWithChildren,
  ApiLinkPreviewImageRoute: ApiLinkPreviewImageRoute,
  ApiSearchRoute: ApiSearchRoute,
  LlmsDotmdxSplatRoute: LlmsDotmdxSplatRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTweetIdRoute: ApiTweetIdRoute,
  OgPostsSplatRoute: OgPostsSplatRoute,
  PostsTagsTagRoute: PostsTagsTagRoute,
  PostsTagsIndexRoute: PostsTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
