/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsUpcomingRouteImport } from './routes/posts/upcoming'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as LlmsDotmdxSplatRouteImport } from './routes/llms[.]mdx.$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as PostsTagsIndexRouteImport } from './routes/posts/tags/index'
import { Route as PostsTagsTagRouteImport } from './routes/posts/tags/$tag'

const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsUpcomingRoute = PostsUpcomingRouteImport.update({
  id: '/posts/upcoming',
  path: '/posts/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxSplatRoute = LlmsDotmdxSplatRouteImport.update({
  id: '/llms.mdx/$',
  path: '/llms.mdx/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsTagsIndexRoute = PostsTagsIndexRouteImport.update({
  id: '/posts/tags/',
  path: '/posts/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsTagsTagRoute = PostsTagsTagRouteImport.update({
  id: '/posts/tags/$tag',
  path: '/posts/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/$': typeof LlmsDotmdxSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/upcoming': typeof PostsUpcomingRoute
  '/posts': typeof PostsIndexRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/posts/tags': typeof PostsTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/$': typeof LlmsDotmdxSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/upcoming': typeof PostsUpcomingRoute
  '/posts': typeof PostsIndexRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/posts/tags': typeof PostsTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/llms.mdx/$': typeof LlmsDotmdxSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/upcoming': typeof PostsUpcomingRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/tags/$tag': typeof PostsTagsTagRoute
  '/posts/tags/': typeof PostsTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/llms-full.txt'
    | '/api/search'
    | '/llms.mdx/$'
    | '/posts/$slug'
    | '/posts/upcoming'
    | '/posts'
    | '/posts/tags/$tag'
    | '/posts/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/llms-full.txt'
    | '/api/search'
    | '/llms.mdx/$'
    | '/posts/$slug'
    | '/posts/upcoming'
    | '/posts'
    | '/posts/tags/$tag'
    | '/posts/tags'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/llms-full.txt'
    | '/api/search'
    | '/llms.mdx/$'
    | '/posts/$slug'
    | '/posts/upcoming'
    | '/posts/'
    | '/posts/tags/$tag'
    | '/posts/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LlmsDotmdxSplatRoute: typeof LlmsDotmdxSplatRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsUpcomingRoute: typeof PostsUpcomingRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsTagsTagRoute: typeof PostsTagsTagRoute
  PostsTagsIndexRoute: typeof PostsTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/upcoming': {
      id: '/posts/upcoming'
      path: '/posts/upcoming'
      fullPath: '/posts/upcoming'
      preLoaderRoute: typeof PostsUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/$': {
      id: '/llms.mdx/$'
      path: '/llms.mdx/$'
      fullPath: '/llms.mdx/$'
      preLoaderRoute: typeof LlmsDotmdxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/tags/': {
      id: '/posts/tags/'
      path: '/posts/tags'
      fullPath: '/posts/tags'
      preLoaderRoute: typeof PostsTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/tags/$tag': {
      id: '/posts/tags/$tag'
      path: '/posts/tags/$tag'
      fullPath: '/posts/tags/$tag'
      preLoaderRoute: typeof PostsTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  LlmsDotmdxSplatRoute: LlmsDotmdxSplatRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsUpcomingRoute: PostsUpcomingRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsTagsTagRoute: PostsTagsTagRoute,
  PostsTagsIndexRoute: PostsTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
